spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
---
spring:
  profiles: dev
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer;INIT=CREATE SCHEMA IF NOT EXISTS "public";
    username: root
    password:
---
spring:
  profiles: nonprod
---
spring:
  profiles: prod
---
spring:
  profiles: test
